version: '3.8'

networks:
  transcendence:
    driver: bridge

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./client:/client
      - client-node-modules:/client/node_modules
    networks:
      - transcendence

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server
      - server-node-modules:/client/node_modules
    networks:
      - transcendence
    command: sh start.sh

  DB_Postgres:
    container_name: DB_Postgres
    image: postgres
    networks:
      - transcendence
    environment:
      POSTGRES_USER: poza
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence
    ports:
      - 5432:5432
    restart: always

volumes:
  client-node-modules:
  server-node-modules:
