version: '3.8'

services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        depends_on:
            - server
        ports:
            - '8000:8000'
        volumes:
            - ./client:/client
            - client-node-modules:/client/node_modules  
        env_file: ./client/.env
        networks:
            - transcendence

    server:
        container_name: server
        env_file: ./server/.env
        depends_on:
            - DB_Postgres
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            -  4000:4000 # ? env
            - '5555:5555'
        volumes:
            - ./server:/server
            - server-node-modules:/server/node_modules
        networks:
            - transcendence
        # command: sh start.sh

    DB_Postgres:
        container_name: DB_Postgres
        image: postgres
        networks:
            - transcendence
        env_file: ./server/.env
        ports:
            - 5432:5432 # ? env
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always

networks:
    transcendence:
        driver: bridge

volumes:
    pgdata:
    client-node-modules:
    server-node-modules:
