version: "3.4"
volumes:
  client:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./client/
services:
 client:
   build: 
      context: ./client/
   container_name: client
   ports:
     - 8000:8000
   volumes:
    - client:/client
   tty: true
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - backendNet