version: "3.4"
volumes:
  client:
    name: client
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./client/
  server:
    name: server
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server/
networks:
  backendNet:
    driver: bridge
services:
  client:
    build: 
      context: ./client/
    container_name: client
    ports:
     - 8000:8000
    volumes:
    - client:/client
    networks:
      - backendNet
    tty: true
  # server:
  #   build:
  #     context: ./server/
  #   container_name: nest-docker-postgres
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
  #   volumes:
  #     - server:/server
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:123@database:5434/nest?schema=public
  #     - JWT_secret=secretJWTforTrandandan
  #   networks:
  #     - backendNet
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: poza
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence
    networks:
      - backendNet
    