version: '3.8'
services:
  DB_Postgres:
    image: postgres
    networks:
      - transcendence
    environment:
      POSTGRES_USER: poza
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence
    ports:
      - 5432:5432
    restart: always
    container_name: DB_Postgres
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - transcendence
    volumes:
      - ./server/:/app/
    ports:
      - 4000:4000
      - 5555:5555
    depends_on:
      - DB_Postgres

    command: sh start.sh
    container_name: server_backEnd
  client:
    build: 
      context: ./client/
    container_name: client
    ports:
     - 8000:8000
    depends_on:
      - server
    command: sh start.sh
networks:
  transcendence:
    driver: bridge